
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jun 29 00:41:42 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 52;
  public static final int GREATER_OR_EQUAL = 27;
  public static final int CONST = 7;
  public static final int EQUALS = 32;
  public static final int CONDITIONAL = 44;
  public static final int BOOL_NOT_EQUAL = 25;
  public static final int CASE = 18;
  public static final int LPAREN = 38;
  public static final int SEMI = 35;
  public static final int GREATER = 26;
  public static final int CONTINUE = 17;
  public static final int NUM_CONST = 51;
  public static final int LESS = 28;
  public static final int MINUS = 20;
  public static final int RPAREN = 39;
  public static final int BOOL_EQUAL = 24;
  public static final int AND = 30;
  public static final int MOD_EQUALS = 49;
  public static final int DIV_EQUALS = 48;
  public static final int LESS_OR_EQUAL = 29;
  public static final int OR = 31;
  public static final int COMMA = 37;
  public static final int CLASS = 4;
  public static final int INC = 33;
  public static final int DIV = 22;
  public static final int PLUS = 19;
  public static final int IF = 8;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int MUL_EQUALS = 47;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int MUL = 21;
  public static final int MOD = 23;
  public static final int IDENT = 53;
  public static final int BREAK = 3;
  public static final int VOID = 15;
  public static final int MINUS_EQUALS = 46;
  public static final int COLON = 36;
  public static final int LBRACE = 42;
  public static final int ELSE = 6;
  public static final int LSQUARE = 40;
  public static final int ENUM = 5;
  public static final int READ = 13;
  public static final int RSQUARE = 41;
  public static final int WHILE = 10;
  public static final int PLUS_EQUALS = 45;
  public static final int RBRACE = 43;
  public static final int EXTENDS = 16;
  public static final int PROG = 2;
  public static final int BOOL_CONST = 50;
  public static final int DEC = 34;
  public static final int PRINT = 12;
  public static final int DO = 9;
}

